### ISSUE TITLE
Redesign Screen "Person Detail"

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#83]
- [ ] create sections by implementing expandable tiles  (#72)
- [ ] add profile picture (#36)
- [ ] improve label filtering
- [ ] implement text editor in comments field (markdown commands)  (#64)

https://www.sketch.com/s/6023b9d5-7942-4477-8970-facb0651c7f4/a/jgexrMW

**Comment by wipascal** [comment]
@frederikbugglin if you can add screenshots of your "next generation" UI, that would be helpful

**Comment by frederikbugglin** [comment]
see issue #104
